name: pub_dev
description: The pub.dev website recreated in Flutter.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  responsive_framework:
    path: responsive_framework
  google_fonts: ^1.1.0
  animations: ^1.1.2
  url_launcher: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/dart_logo_full.png"
  image_path_ios: "assets/dart_logo_full.png"
  adaptive_icon_background: "#FFFFFFFF"
  adaptive_icon_foreground: "assets/dart_logo_adaptive.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/fonts/product_sans_regular.ttf
        - asset: assets/fonts/product_sans_bold.ttf
          weight: 700
        - asset: assets/fonts/product_sans_italic.ttf
          style: italic
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_regular.ttf
        - asset: assets/fonts/roboto_bold.ttf
          weight: 700
        - asset: assets/fonts/roboto_italic.ttf
          style: italic