name: pub_dev
description: The pub.dev website recreated in Flutter.
version: 1.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  responsive_framework:
    path: responsive_framework
  google_fonts: ^2.0.0
  animations: ^2.0.0
  url_launcher: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/dart_logo_full.png"
  image_path_ios: "assets/dart_logo_full.png"
  adaptive_icon_background: "#FFFFFFFF"
  adaptive_icon_foreground: "assets/dart_logo_adaptive.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/fonts/product_sans_regular.ttf
        - asset: assets/fonts/product_sans_bold.ttf
          weight: 700
        - asset: assets/fonts/product_sans_italic.ttf
          style: italic
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_regular.ttf
        - asset: assets/fonts/roboto_bold.ttf
          weight: 700
        - asset: assets/fonts/roboto_italic.ttf
          style: italic