name: pub_dev
publish_to: none
description: The pub.dev website recreated in Flutter.
version: 1.1.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  responsive_framework:
    path: responsive_framework
  google_fonts: ^6.1.0
  animations: ^2.0.11
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/dart_logo_full.png"
  image_path_android: "assets/dart_logo_full.png"
  image_path_ios: "assets/dart_logo_full.png"
  adaptive_icon_background: "#FFFFFFFF"
  adaptive_icon_foreground: "assets/dart_logo_adaptive.png"
  web:
    generate: true
  macos:
    generate: true
  windows:
    generate: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/fonts/product_sans_regular.ttf
        - asset: assets/fonts/product_sans_bold.ttf
          weight: 700
        - asset: assets/fonts/product_sans_italic.ttf
          style: italic
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_regular.ttf
        - asset: assets/fonts/roboto_bold.ttf
          weight: 700
        - asset: assets/fonts/roboto_italic.ttf
          style: italic